import type { NodePgDatabase, NodePgTransaction } from 'drizzle-orm/node-postgres'

import { indicatorHierarchy } from '../schema'
import type { NewIndicatorHierarchy } from '../schema'

type DatabaseClient = NodePgDatabase | NodePgTransaction<any, any>

export const aguaDoceIndicatorIds = {
  IVCaq: '00000000-0000-0000-0000-000000000100',
  Exposicao: '00000000-0000-0000-0000-000000000101',
  Sensibilidade: '00000000-0000-0000-0000-000000000102',
  CapacidadeAdaptativa: '00000000-0000-0000-0000-000000000103',
  Agricultura: '00000000-0000-0000-0000-000000000201',
  Mineracao: '00000000-0000-0000-0000-000000000202',
  AreaUrbana: '00000000-0000-0000-0000-000000000203',
  Pastagens: '00000000-0000-0000-0000-000000000204',
  Silvicultura: '00000000-0000-0000-0000-000000000205',
  PrecipitacaoVar: '00000000-0000-0000-0000-000000000206',
  TmaxVar: '00000000-0000-0000-0000-000000000207',
  IFPNorm: '00000000-0000-0000-0000-000000000301',
  DisFPeixes: '00000000-0000-0000-0000-000000000302',
  DisFBentos: '00000000-0000-0000-0000-000000000303',
  PropMacNN: '00000000-0000-0000-0000-000000000304',
  PropMacEPT: '00000000-0000-0000-0000-000000000305',
  PropPeixesNN: '00000000-0000-0000-0000-000000000306',
  PropPeixesEnd: '00000000-0000-0000-0000-000000000307',
  PropPeixesAm: '00000000-0000-0000-0000-000000000308',
  PropPeixesMigr: '00000000-0000-0000-0000-000000000309',
  RedFBentos: '00000000-0000-0000-0000-00000000030a',
  RedFPeixes: '00000000-0000-0000-0000-00000000030b',
  PropBentN: '00000000-0000-0000-0000-00000000030c',
  ICL: '00000000-0000-0000-0000-00000000030d',
  UCperc: '00000000-0000-0000-0000-000000000401',
  PropPeixN: '00000000-0000-0000-0000-000000000402',
} as const

const indicatorHierarchyData: NewIndicatorHierarchy[] = [
  {
    id: aguaDoceIndicatorIds.IVCaq,
    workgroupId: 'agua-doce',
    code: 'IVCaq',
    name: 'Índice de Vulnerabilidade Climática Aquática',
    type: 'indice',
    parentId: null,
    order: 1,
    description:
      'Índice composto que sintetiza exposição, sensibilidade e capacidade adaptativa das sub-bacias.',
  },
  {
    id: aguaDoceIndicatorIds.Exposicao,
    workgroupId: 'agua-doce',
    code: 'Exposicao',
    name: 'Exposição',
    type: 'subindice',
    parentId: aguaDoceIndicatorIds.IVCaq,
    order: 1,
    description: 'Indicadores que representam pressões antrópicas e climáticas.',
  },
  {
    id: aguaDoceIndicatorIds.Sensibilidade,
    workgroupId: 'agua-doce',
    code: 'Sensibilidade',
    name: 'Sensibilidade',
    type: 'subindice',
    parentId: aguaDoceIndicatorIds.IVCaq,
    order: 2,
    description:
      'Indicadores relacionados à biodiversidade aquática e resposta ecológica às pressões externas.',
  },
  {
    id: aguaDoceIndicatorIds.CapacidadeAdaptativa,
    workgroupId: 'agua-doce',
    code: 'CapacidadeAdaptativa',
    name: 'Capacidade Adaptativa',
    type: 'subindice',
    parentId: aguaDoceIndicatorIds.IVCaq,
    order: 3,
    description:
      'Indicadores que refletem a capacidade institucional e ecológica de adaptação às mudanças.',
  },
  {
    id: aguaDoceIndicatorIds.Agricultura,
    workgroupId: 'agua-doce',
    code: 'Agricultura',
    name: 'Agricultura',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Exposicao,
    order: 1,
    unit: '% área',
    description: 'Proporção de área agrícola na sub-bacia.',
  },
  {
    id: aguaDoceIndicatorIds.Mineracao,
    workgroupId: 'agua-doce',
    code: 'Mineracao',
    name: 'Mineração',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Exposicao,
    order: 2,
    unit: '% área',
    description: 'Área impactada por mineração em relação à área total da sub-bacia.',
  },
  {
    id: aguaDoceIndicatorIds.AreaUrbana,
    workgroupId: 'agua-doce',
    code: 'Area_urbana',
    name: 'Área Urbana',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Exposicao,
    order: 3,
    unit: '% área',
    description: 'Proporção de área urbanizada na sub-bacia.',
  },
  {
    id: aguaDoceIndicatorIds.Pastagens,
    workgroupId: 'agua-doce',
    code: 'Pastagens',
    name: 'Pastagens',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Exposicao,
    order: 4,
    unit: '% área',
    description: 'Cobertura de pastagens em relação à área total.',
  },
  {
    id: aguaDoceIndicatorIds.Silvicultura,
    workgroupId: 'agua-doce',
    code: 'Silvicultura',
    name: 'Silvicultura',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Exposicao,
    order: 5,
    unit: '% área',
    description: 'Área ocupada por silvicultura.',
  },
  {
    id: aguaDoceIndicatorIds.PrecipitacaoVar,
    workgroupId: 'agua-doce',
    code: 'Precipitacao_var',
    name: 'Variação de Precipitação',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Exposicao,
    order: 6,
    unit: 'mm',
    description: 'Variação anual de precipitação projetada.',
  },
  {
    id: aguaDoceIndicatorIds.TmaxVar,
    workgroupId: 'agua-doce',
    code: 'Tmax_var',
    name: 'Variação de Temperatura Máxima',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Exposicao,
    order: 7,
    unit: '°C',
    description: 'Projeção de aumento na temperatura máxima anual.',
  },
  {
    id: aguaDoceIndicatorIds.PropPeixesNN,
    workgroupId: 'agua-doce',
    code: 'Prop_peixesNN',
    name: 'Peixes Não Nativos',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Exposicao,
    order: 8,
    unit: '% espécies',
    description: 'Proporção de peixes não nativos.',
  },
  {
    id: aguaDoceIndicatorIds.PropMacNN,
    workgroupId: 'agua-doce',
    code: 'Prop_MacNN',
    name: 'Macroinvertebrados Não Nativos',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Exposicao,
    order: 9,
    unit: '% espécies',
    description: 'Proporção de macroinvertebrados não nativos registrados.',
  },
  {
    id: aguaDoceIndicatorIds.IFPNorm,
    workgroupId: 'agua-doce',
    code: 'IFP_norm',
    name: 'IFP Normalizado',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Exposicao,
    order: 10,
    unit: 'índice',
    description: 'Índice de Fragmentação de Paisagens normalizado.',
  },
  {
    id: aguaDoceIndicatorIds.DisFPeixes,
    workgroupId: 'agua-doce',
    code: 'disF_peixes',
    name: 'Distribuição Funcional de Peixes',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Sensibilidade,
    order: 1,
    unit: 'índice',
    description: 'Diversidade funcional de comunidades de peixes.',
  },
  {
    id: aguaDoceIndicatorIds.DisFBentos,
    workgroupId: 'agua-doce',
    code: 'disF_bentos',
    name: 'Distribuição Funcional de Bentos',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Sensibilidade,
    order: 2,
    unit: 'índice',
    description: 'Diversidade funcional de macroinvertebrados bentônicos.',
  },
  {
    id: aguaDoceIndicatorIds.PropPeixesEnd,
    workgroupId: 'agua-doce',
    code: 'Prop_peixesEnd',
    name: 'Peixes Endêmicos',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Sensibilidade,
    order: 3,
    unit: '% espécies',
    description: 'Proporção de espécies endêmicas.',
  },
  {
    id: aguaDoceIndicatorIds.PropPeixesAm,
    workgroupId: 'agua-doce',
    code: 'Prop_peixesAm',
    name: 'Peixes Ameaçados',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Sensibilidade,
    order: 4,
    unit: '% espécies',
    description: 'Proporção de espécies ameaçadas na sub-bacia.',
  },
  {
    id: aguaDoceIndicatorIds.PropMacEPT,
    workgroupId: 'agua-doce',
    code: 'Prop_MacEPT',
    name: 'Macroinvertebrados EPT',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Sensibilidade,
    order: 5,
    unit: '% espécies',
    description: 'Proporção de ordens Ephemeroptera, Plecoptera e Trichoptera.',
  },
  {
    id: aguaDoceIndicatorIds.PropPeixesMigr,
    workgroupId: 'agua-doce',
    code: 'Prop_peixesMigr',
    name: 'Peixes Migratórios',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.Sensibilidade,
    order: 6,
    unit: '% espécies',
    description: 'Proporção de espécies migratórias.',
  },
  {
    id: aguaDoceIndicatorIds.RedFBentos,
    workgroupId: 'agua-doce',
    code: 'redF_bentos',
    name: 'Redução Funcional de Bentos',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.CapacidadeAdaptativa,
    order: 1,
    unit: 'índice',
    description: 'Redução do papel funcional de macroinvertebrados bentônicos.',
  },
  {
    id: aguaDoceIndicatorIds.ICL,
    workgroupId: 'agua-doce',
    code: 'ICL',
    name: 'Índice de Conservação de Lagos',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.CapacidadeAdaptativa,
    order: 2,
    unit: 'índice',
    description: 'Índice composto de conservação de ambientes lacustres.',
  },
  {
    id: aguaDoceIndicatorIds.RedFPeixes,
    workgroupId: 'agua-doce',
    code: 'redF_peixes',
    name: 'Redução Funcional de Peixes',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.CapacidadeAdaptativa,
    order: 3,
    unit: 'índice',
    description: 'Redução do papel funcional de peixes nativos.',
  },
  {
    id: aguaDoceIndicatorIds.PropBentN,
    workgroupId: 'agua-doce',
    code: 'Prop_Bent_N',
    name: 'Bentônicos Não Nativos',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.CapacidadeAdaptativa,
    order: 4,
    unit: '% espécies',
    description: 'Proporção de bentônicos não nativos.',
  },
  {
    id: aguaDoceIndicatorIds.UCperc,
    workgroupId: 'agua-doce',
    code: 'UC_perc',
    name: 'Unidades de Conservação',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.CapacidadeAdaptativa,
    order: 5,
    unit: '% área',
    description: 'Percentual da sub-bacia protegido por unidades de conservação.',
  },
  {
    id: aguaDoceIndicatorIds.PropPeixN,
    workgroupId: 'agua-doce',
    code: 'Prop_Peix_N',
    name: 'Peixes Nativos',
    type: 'indicador',
    parentId: aguaDoceIndicatorIds.CapacidadeAdaptativa,
    order: 6,
    unit: '% espécies',
    description: 'Proporção de peixes nativos presentes.',
  },
]

export async function seedAguaDoceIndicatorHierarchy(db: DatabaseClient) {
  await db
    .insert(indicatorHierarchy)
    .values(indicatorHierarchyData)
    .onConflictDoNothing()
}
